version: 1.0.{build}

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
  - nuget-restore src\hwDataLibrary.sln

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

platform: x64

configuration: Debug
  
build:
  project: src/hwDataLibrary.sln
  verbosity: Minimal 
  publish_nuget: true